- name: "Početna"
  link: "/"
- name: "Proizvodi"
  link: "/proizvodi"
- name: "Naruči"
  link: "/naruci"
- name: "Projekti"
  link: "/projekti"
- name: "Instagram"
  link: "/instagram"
- name: "O nama"
  link: "/o-nama"